version: "3"
services:
  jenkins:
    image: pyjenkins
    container_name: "jenkins_caio"
    ports:
      - "8032:8080"
      - "50000:50000"
    volumes: 
      - "./jenkins_home:/var/jenkins_home"
      - "./cambio:/cambio"

