name: Deploy Data Platform to Production

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v2

    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: install dependencies
      run: make ci-setup

    - name: do test
      run: make ci-test

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v2

    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: install dependencies
      run: make ci-setup
 
    - name: Deploy
      env: 
        AWS_ACESS_KEY_ID: $({{secrets.AWS_ACESS_KEY_ID}})]
        AWS_SECRET_ACESS_KEY: $({{secrets.AWS_SECRET_ACESS_KEY}})
        AWS_DEFAULT_REGION: $({{secrets.AWS_DEFAULT_REGION}})
      run: ci-deploy stage=prod